-- Seed: 38 verified target accounts (docs/research/02-target-accounts.md §1.1) and the first 15
-- outreach hooks (§5) as leads in stage 'identified'. Idempotent: accounts upsert on name; a lead
-- is created only if the account has no lead yet. Domains are derived only from evidence URLs on
-- the company's own site; everything else stays null until verified. No outreach is sent from here.
set search_path to ps, public;

insert into ps.accounts (name, domain, country, segment, priority, why_they_care, evidence_urls) values
 ($$Niron Magnetics$$, 'nironmagnetics.com', 'US', 'magnet_producer', 'A', $$Iron-nitride (Fe16N2) "Clean Earth Magnet"; raised US$33M (Nov 2023, GM Ventures, Stellantis Ventures, Volvo Cars) and US$25M (Feb 2024, Samsung Ventures, Magna, Allison); opened a commercial plant; needs competitor-patent watch and partner intelligence.$$, array['https://nironmagnetics.com/niron-magnetics-secures-33m-from-leading-automotive-manufacturers-to-meet-growing-demand-for-rare-earth-free-magnets/','https://interestingengineering.com/science/rare-earth-free-magnets-niron-magnets']),
 ($$General Motors$$, null, 'US', 'automaker', 'A', $$Niron investor (2023, again Aug 2025); Marquette-Niron-GM RE-free drivetrain programme (2020); multi-year Noveon magnet supply deal (Aug 2025).$$, array['https://www.businesswire.com/news/home/20201120005152/en/Niron-Magnetics-Partners-with-Marquette-University-and-General-Motors-to-Develop-Drivetrains-for-Electric-Vehicles-using-Rare-Earth-Free-Materials','https://www.prnewswire.com/news-releases/driving-american-industry-general-motors--noveon-magnetics-sign-multi-year-agreement-to-deliver-american-made-rare-earth-magnets-302522804.html']),
 ($$Stellantis$$, null, 'NL', 'automaker', 'A', $$Stellantis Ventures in Niron's US$33M round; separate Niron-Stellantis partnership on RE-free e-motor technology.$$, array['https://autotechinsight.spglobal.com/news/5284624/niron-magnetics-partners-with-stellantis-for-rare-earth-free-electric-motor-technology']),
 ($$Honda Motor$$, null, 'JP', 'automaker', 'A', $$Invested in Niron (2025), the newest OEM to back iron-nitride magnets.$$, array['https://www.manufacturingdive.com/news/honda-invests-in-us-maker-of-rare-earth-free-magnets/830283/']),
 ($$Tesla$$, null, 'US', 'automaker', 'A', $$2023 Investor Day: next-gen PMSM with zero rare earths; Sept 2026: Cybercab motor confirmed RE-free PM motor (ferrite or iron nitride discussed). Inbound target only (in-house patent posture).$$, array['https://www.adamasintel.com/tesla-rare-earth-free-motor/','https://electrek.co/2026/09/04/teslas-new-rare-earth-free-ev-motor-is-a-big-deal-but-not-that-big-a-deal/']),
 ($$BMW Group$$, 'bmwgroup.com', 'DE', 'automaker', 'A', $$Gen5 and Gen6 eDrive use electrically excited (wound-rotor) synchronous motors with no rare-earth magnets; award-winning; Neue Klasse 800V.$$, array['https://www.press.bmwgroup.com/canada/article/detail/T0440602EN/bmw%E2%80%99s-5th-generation-electric-drive-system-wins-2024-ajac-best-green-innovation-award?language=en','https://www.emobility-engineering.com/bmw-gen6-two-motor-800v-edrive-cylindrical-battery/']),
 ($$Renault Group / Ampere$$, 'renaultgroup.com', 'FR', 'automaker', 'A', $$Wound-rotor pioneer since 2012; E7A 200 kW RE-free motor; 2025 shift to in-house development with possible Chinese stator supplier after ending Valeo tie-up.$$, array['https://www.renaultgroup.com/en/magazine/energy-and-powertrains/e7a-the-next-gen-electric-motor-developed-by-renault-and-valeo/','https://www.marketscreener.com/news/renault-may-develop-new-rare-earth-free-motor-with-chinese-supplier-ce7d5fd8da8ff226']),
 ($$Valeo$$, null, 'FR', 'emotor', 'B', $$Co-developed E7A stator (hairpin) for RE-free motor; partnership ended - Valeo now needs to reposition its RE-free IP.$$, array['https://www.evengineeringonline.com/renault-and-valeo-design-electric-motor-requiring-no-rare-earth-elements/','https://www.tekedia.com/renault-ends-rare-earth-free-motor-partnership-with-valeo-turns-to-china-for-cheaper-components/']),
 ($$ZF Friedrichshafen$$, 'zf.com', 'DE', 'emotor', 'A', $$I2SM in-rotor inductive-excited synchronous motor, magnet-free, up to 50% lower CO2 vs PSM; presented as production-ready alternative.$$, array['https://press.zf.com/press/en/releases/release_60480.html']),
 ($$MAHLE$$, 'mahle.com', 'DE', 'emotor', 'A', $$MCT magnet-free contactless-transmitter motor (>95% efficiency); "perfect motor" kit combining SCT + MCT, explicitly "absence of rare earths".$$, array['https://newsroom.mahle.com/press/en/press-releases/mahle-develops-highly-efficient-magnet-free-electric-motor--82368','https://newsroom.mahle.com/press/en/press-releases/perfect-motor-mahle-combines-strengths-of-its-sct-and-mct-electric-motors-99968']),
 ($$Toyota Motor$$, 'global.toyota', 'JP', 'automaker', 'A', $$Nd-reduced magnet substituting La/Ce for up to 50% of Nd, Dy/Tb-free; targets drive motors, EPS, appliances - a Ce/La-substitution patent leader.$$, array['https://global.toyota/en/newsroom/corporate/21139684.html']),
 ($$Nidec$$, null, 'JP', 'emotor', 'A', $$Nidec SR Drives magnet-free switched-reluctance motors (Land Rover Defender demos); Noveon supply agreement shows active magnet sourcing.$$, array['https://interestingengineering.com/case-studies/ev-motors-rare-earth-magnets','https://chargedevs.com/newswire/noveon-magnetics-to-supply-rare-earth-magnets-to-nidec-motor/']),
 ($$Hitachi Astemo$$, 'astemo.com', 'JP', 'emotor', 'A', $$Announced a new rare-earth-free motor (27 Oct 2025 release).$$, array['https://www.astemo.com/en/news/20251027-01/']),
 ($$Proterial$$, 'proterial.com', 'JP', 'magnet_producer', 'A', $$Prototype EV motor with ferrite (NMF) magnets, no Nd; July 2025 heavy-RE-free NdFeB sintered magnet for EV drive motors; sells materials, not motors.$$, array['https://www.proterial.com/e/press/2025/n0722b.html','https://autotechinsight.spglobal.com/news/5271728/japans-proterial-develops-new-ev-motor-to-cut-down-usage-of-rare-earth-magnets']),
 ($$Vacuumschmelze (VAC) / eVAC Magnetics$$, 'vacuumschmelze.com', 'DE', 'magnet_producer', 'A', $$VACODYM 902 TP heavy-RE-free NdFeB; Sumter, SC plant (opened July, DoD-funded); Ucore oxide alliance; Cyclic recycling deal - dense IP-monitoring need.$$, array['https://vacuumschmelze.com/Newsroom/vacodym-902-tp-heavy-rare-earth-free-permanent-magnets-n2833','https://evac-magnetics.com/','https://ucore.com/ucore-announces-strategic-alliance-with-vacuumschmelze-and-evac-magnetics-llc-for-the-supply-of-rare-earth-oxides/']),
 ($$TDK$$, 'tdk.com', 'JP', 'magnet_producer', 'A', $$World's first La-Co high-performance ferrite (FB series); HAL heavy-RE diffusion; one of largest ferrite operations globally.$$, array['https://product.tdk.com/en/products/magnet/index.html','https://product.tdk.com/en/products/magnet/magnet/ferrite/index.html']),
 ($$Shin-Etsu Chemical$$, 'shinetsu-rare-earth-magnet.jp', 'JP', 'magnet_producer', 'B', $$Grain-boundary-diffusion patent family reducing heavy RE; explicitly refuses third-party licences - a patent-aggressive incumbent to monitor.$$, array['https://www.shinetsu-rare-earth-magnet.jp/e/topics/detail_21.html','https://www.shinetsu-rare-earth-magnet.jp/e/rd/grain.html']),
 ($$Arnold Magnetic Technologies$$, 'arnoldmagnetics.com', 'US', 'magnet_producer', 'A', $$ARNOX hard ferrite, RECOMA SmCo, ITAR/DFARS compliant; participates in university/lab R&D on RE processing and materials.$$, array['https://www.arnoldmagnetics.com/','https://pdf.directindustry.com/pdf/arnold-magnetic-technologies/hard-ferrite-material/7281-109185.html']),
 ($$Advanced Magnet Lab (AML)$$, null, 'US', 'magnet_producer', 'B', $$PM-Wire process; DOE award for motor project; US$2M DLA contract (May 2026) to qualify US-made NdFeB - small firm with a patent-centric strategy.$$, array['https://magneticsmag.com/aml-moves-ahead-on-pm-wire-development-and-doe-award-for-motor-project/','https://www.globenewswire.com/news-release/2026/05/19/3297390/0/en/advanced-magnet-lab-aml-awarded-2-million-defense-logistics-agency-dla-contract-to-qualify-innovative-100-u-s-made-high-grade-sintered-ndfeb-permanent-magnets-for-defense.html']),
 ($$Noveon Magnetics$$, 'noveon.co', 'US', 'magnet_producer', 'A', $$Only operational US sintered NdFeB maker; EcoFlux recycled magnets; GM (Aug 2025), ABB and Nidec supply deals - must track RE-free substitutes threatening its market.$$, array['https://noveon.co/general-motors-noveon-magnetics-sign-multi-year-agreement','https://magneticsmag.com/abb-selects-noveon-magnetics-for-long-term-agreement-to-supply-u-s-made-rare-earth-magnets/']),
 ($$MP Materials$$, 'mpmaterials.com', 'US', 'materials_chemicals', 'A', $$DoD partnership (July 2025, US$400M preferred, 10X facility to 10,000 t/yr by 2028); Apple US$500M recycled-magnet deal; US$58.5M award - the incumbent most exposed to substitution.$$, array['https://investors.mpmaterials.com/investor-news/news-details/2025/MP-Materials-and-Apple-Announce-500-Million-Partnership-to-Produce-Recycled-Rare-Earth-Magnets-in-the-United-States/default.aspx','https://www.sec.gov/Archives/edgar/data/1801368/000180136826000008/mp-20251231.htm']),
 ($$Vulcan Elements$$, null, 'US', 'magnet_producer', 'C', $$Emerging US magnet maker surfaced alongside VAC/DoD magnet-supply coverage.$$, array['https://en.wikipedia.org/wiki/Vulcan_Elements']),
 ($$Volvo Cars$$, null, 'SE', 'automaker', 'B', $$Participated in Niron's US$33M round (Nov 2023).$$, array['https://nironmagnetics.com/niron-magnetics-secures-33m-from-leading-automotive-manufacturers-to-meet-growing-demand-for-rare-earth-free-magnets/']),
 ($$Samsung (Samsung Ventures)$$, null, 'KR', 'consumer_electronics', 'B', $$Led Niron's US$25M round (Feb 2024); magnets in appliances, HDD/consumer motors.$$, array['https://www.wardsauto.com/news/archive-auto-samsung-magna-allison-transmission-invest-25m-niron-magnetics/708382/']),
 ($$Magna International$$, null, 'CA', 'emotor', 'B', $$Niron investor (Feb 2024); e-drive supplier.$$, array['https://nironmagnetics.com/niron-magnetics-secures-funding-from-samsung-ventures-allison-transmission-and-magna-to-accelerate-production-of-rare-earth-free-magnets/']),
 ($$Allison Transmission (Allison Ventures)$$, null, 'US', 'emotor', 'B', $$Niron investor (Feb 2024); electrified commercial-vehicle propulsion.$$, array['https://magneticsmag.com/niron-magnetics-secures-funding-from-samsung-ventures-auto-heavyweights-to-accelerate-production-of-rare-earth-free-magnets/']),
 ($$ABB$$, null, 'CH', 'industrial_motors', 'B', $$Long-term agreement with Noveon for US-made magnets - active magnet-supply strategy for motors and drives.$$, array['https://magneticsmag.com/abb-selects-noveon-magnetics-for-long-term-agreement-to-supply-u-s-made-rare-earth-magnets/']),
 ($$Apple$$, null, 'US', 'consumer_electronics', 'B', $$US$500M MP Materials partnership for recycled magnets (July 2025); shipments from 2027 for "hundreds of millions" of devices.$$, array['https://investors.mpmaterials.com/investor-news/news-details/2025/MP-Materials-and-Apple-Announce-500-Million-Partnership-to-Produce-Recycled-Rare-Earth-Magnets-in-the-United-States/default.aspx']),
 ($$Vestas Wind Systems$$, 'vestas.com', 'DK', 'wind', 'A', $$Corporate policy: geared drivetrains use up to 10x less RE than direct drive; phasing out Dy/Tb in recent models.$$, array['https://www.vestas.com/en/sustainability/environment/materials-and-rare-earths']),
 ($$Siemens Gamesa (Siemens Energy)$$, null, 'ES', 'wind', 'A', $$Direct-drive PM generators; COO confirmed talks with Chinese magnet suppliers on European production; long-term RE supply deals.$$, array['https://www.investing.com/news/stock-market-news/siemens-gamesa-chinese-magnet-suppliers-discuss-european-production-coo-says-4113338','https://www.windpowermonthly.com/article/1819209/siemens-gamesa-secures-rare-earth-materials-offshore-wind-turbines']),
 ($$GE Vernova$$, null, 'US', 'wind', 'C', $$Offshore Haliade-X direct-drive PM generators; S-1 risk factors on materials. No RE-free statement found.$$, array['https://www.sec.gov/Archives/edgar/data/1996810/000119312524131304/d783090ds1a.htm']),
 ($$Goldwind$$, 'goldwindamericas.com', 'CN', 'wind', 'B', $$World's #1 installer (18.7 GW in 2024) on PMDD; some magnets now Dy-free - a large consumer with substitution incentive.$$, array['https://www.goldwindamericas.com/pmdd','https://www.windpowermonthly.com/article/1519221/rethinking-use-rare-earth-elements']),
 ($$GreenSpur Wind$$, 'greenspur.co.uk', 'GB', 'wind', 'B', $$15 MW RE-free generator using Niron Gen-1 FeN magnets; 56% mass reduction, ORE Catapult-verified.$$, array['https://www.greenspur.co.uk/niron/','https://www.offshorewind.biz/2022/07/28/15-mw-rare-earth-free-offshore-wind-turbine-seeks-path-to-market/']),
 ($$Cyclic Materials$$, 'cyclicmaterials.earth', 'CA', 'materials_chemicals', 'C', $$10-year deal to recycle VAC's Sumter magnet-production waste.$$, array['https://cyclicmaterials.earth/resources/cyclic-materials-and-vacuumschmelze-expand-partnership-to-recycle-rare-earth-magnet-manufacturing-waste-in-the-u-s']),
 ($$Ucore Rare Metals$$, 'ucore.com', 'CA', 'materials_chemicals', 'C', $$Strategic alliance to supply separated REOs to VAC/eVAC.$$, array['https://ucore.com/ucore-announces-strategic-alliance-with-vacuumschmelze-and-evac-magnetics-llc-for-the-supply-of-rare-earth-oxides/']),
 ($$Ames National Laboratory / Critical Materials Innovation Hub (CMI)$$, 'ameslab.gov', 'US', 'research_institute', 'B', $$Programme on improving RE-free magnets via microstructure engineering; DOE hub that licenses to industry.$$, array['https://www.ameslab.gov/news/improving-rare-earth-free-magnets-through-microstructure-engineering']),
 ($$University of Minnesota$$, null, 'US', 'research_institute', 'B', $$Origin of the Fe16N2 iron-nitride technology commercialised by Niron; foundational patent estate.$$, array['https://interestingengineering.com/innovation/rare-earth-free-magnet-help-us']),
 ($$Marquette University$$, null, 'US', 'research_institute', 'C', $$RE-free EV drivetrain programme with Niron and GM (2020).$$, array['https://www.businesswire.com/news/home/20201120005152/en/Niron-Magnetics-Partners-with-Marquette-University-and-General-Motors-to-Develop-Drivetrains-for-Electric-Vehicles-using-Rare-Earth-Free-Materials'])
on conflict (name) do update set
  domain = coalesce(ps.accounts.domain, excluded.domain),
  country = excluded.country, segment = excluded.segment, priority = excluded.priority,
  why_they_care = excluded.why_they_care, evidence_urls = excluded.evidence_urls;

-- First 15 hooks (§5 ranking). One factual sentence + evidence URL; source and legitimate-interest
-- rationale recorded per §4.9. Contact is null until a public B2B path is verified (§4).
with hooks(rank, account, hook, url) as (values
 (1,  $$Niron Magnetics$$, $$Niron's Sartell, MN plant received a conditional US$150M, 20-year loan commitment from the Office of Strategic Capital on 7 Aug 2026, with the plant due to be operational in 2027.$$, 'https://www.war.gov/News/Releases/Release/Article/4566567/office-of-strategic-capital-signs-150-million-conditional-loan-commitment-with/'),
 (2,  $$General Motors$$, $$GM signed a multi-year agreement with Noveon Magnetics in Aug 2025 for American-made rare-earth magnets while remaining an investor in rare-earth-free Niron.$$, 'https://www.prnewswire.com/news-releases/driving-american-industry-general-motors--noveon-magnetics-sign-multi-year-agreement-to-deliver-american-made-rare-earth-magnets-302522804.html'),
 (3,  $$Stellantis$$, $$Stellantis and Niron Magnetics announced a partnership on rare-earth-free electric-motor technology, in addition to Stellantis Ventures' stake in Niron's US$33M round.$$, 'https://autotechinsight.spglobal.com/news/5284624/niron-magnetics-partners-with-stellantis-for-rare-earth-free-electric-motor-technology'),
 (4,  $$Honda Motor$$, $$Honda invested in Niron Magnetics in 2025, becoming the newest automaker to back iron-nitride magnets.$$, 'https://www.manufacturingdive.com/news/honda-invests-in-us-maker-of-rare-earth-free-magnets/830283/'),
 (5,  $$Proterial$$, $$Proterial announced a heavy-rare-earth-free NdFeB sintered magnet for EV drive motors on 22 July 2025, alongside its ferrite (NMF) prototype EV motor.$$, 'https://www.proterial.com/e/press/2025/n0722b.html'),
 (6,  $$Vacuumschmelze (VAC) / eVAC Magnetics$$, $$VAC launched VACODYM 902 TP, a heavy-rare-earth-free NdFeB grade, and opened the DoD-funded eVAC plant in Sumter, SC in July.$$, 'https://vacuumschmelze.com/Newsroom/vacodym-902-tp-heavy-rare-earth-free-permanent-magnets-n2833'),
 (7,  $$ZF Friedrichshafen$$, $$ZF presented the I2SM, an in-rotor inductively excited synchronous motor with no magnets, as a production-ready alternative with up to 50% lower CO2 footprint than a PSM.$$, 'https://press.zf.com/press/en/releases/release_60480.html'),
 (8,  $$MAHLE$$, $$MAHLE positioned its SCT + MCT combination as the "perfect motor", explicitly citing the absence of rare earths in the magnet-free MCT design.$$, 'https://newsroom.mahle.com/press/en/press-releases/perfect-motor-mahle-combines-strengths-of-its-sct-and-mct-electric-motors-99968'),
 (9,  $$Renault Group / Ampere$$, $$Renault ended the E7A rare-earth-free motor collaboration with Valeo in 2025 and is considering a Chinese stator supplier while developing in-house.$$, 'https://www.marketscreener.com/news/renault-may-develop-new-rare-earth-free-motor-with-chinese-supplier-ce7d5fd8da8ff226'),
 (10, $$BMW Group$$, $$BMW's Gen6 eDrive for the Neue Klasse keeps the electrically excited synchronous motor with no rare-earth magnets, now on an 800V architecture.$$, 'https://www.emobility-engineering.com/bmw-gen6-two-motor-800v-edrive-cylindrical-battery/'),
 (11, $$Toyota Motor$$, $$Toyota's neodymium-reduced magnet substitutes lanthanum and cerium for up to 50% of the neodymium and eliminates dysprosium and terbium, targeting drive motors, EPS and appliances.$$, 'https://global.toyota/en/newsroom/corporate/21139684.html'),
 (12, $$Hitachi Astemo$$, $$Hitachi Astemo announced a new rare-earth-free motor in its 27 Oct 2025 release.$$, 'https://www.astemo.com/en/news/20251027-01/'),
 (13, $$Noveon Magnetics$$, $$Noveon Magnetics, the only operational US sintered NdFeB maker, signed supply agreements with GM, ABB and Nidec, so rare-earth-free substitutes directly threaten its addressable market.$$, 'https://noveon.co/general-motors-noveon-magnetics-sign-multi-year-agreement'),
 (14, $$TDK$$, $$TDK markets the FB series, the world's first La-Co high-performance ferrite, and runs one of the largest ferrite magnet operations globally.$$, 'https://product.tdk.com/en/products/magnet/magnet/ferrite/index.html'),
 (15, $$Arnold Magnetic Technologies$$, $$Arnold Magnetic Technologies produces ARNOX hard ferrite and RECOMA SmCo magnets under ITAR/DFARS compliance for defense customers.$$, 'https://www.arnoldmagnetics.com/')
)
insert into ps.leads (account_id, stage, owner_agent, next_action, notes)
select a.id, 'identified', 'prospecting',
  'Verify a public B2B contact path (attorney of record / IP page / press contact) before any outreach; blocked until outreach domain, mailbox and legal/REVIEW_STATUS.md allow it.',
  format(E'Outreach rank: %s of 15 (docs/research/02-target-accounts.md §5).\nHook: %s\nEvidence: %s\nSource of account: desk research 2026-09-25 (public press releases and trade media).\nLawful basis: legitimate interest, B2B, role-relevant (IP / R&D / strategy). Opt-out honoured via ps.do_not_contact.', h.rank, h.hook, h.url)
from hooks h join ps.accounts a on a.name = h.account
where not exists (select 1 from ps.leads l where l.account_id = a.id);
